export const arrayOfContients = [
  {
    "America":[
      {
        "common":"Colombia",
        "cca2":"CO"
      },
      {
        "common":"Curaçao",
        "cca2":"CW"
      },
      {
        "common":"French Guiana",
        "cca2":"GF"
      },
      {
        "common":"Grenada",
        "cca2":"GD"
      },
      {
        "common":"Sint Maarten",
        "cca2":"SX"
      },
      {
        "common":"Argentina",
        "cca2":"AR"
      },
      {
        "common":"Turks and Caicos Islands",
        "cca2":"TC"
      },
      {
        "common":"Dominica",
        "cca2":"DM"
      },
      {
        "common":"United States Minor Outlying Islands",
        "cca2":"UM"
      },
      {
        "common":"Costa Rica",
        "cca2":"CR"
      },
      {
        "common":"Haiti",
        "cca2":"HT"
      },
      {
        "common":"Barbados",
        "cca2":"BB"
      },
      {
        "common":"Honduras",
        "cca2":"HN"
      },
      {
        "common":"Puerto Rico",
        "cca2":"PR"
      },
      {
        "common":"Falkland Islands",
        "cca2":"FK"
      },
      {
        "common":"Saint Kitts and Nevis",
        "cca2":"KN"
      },
      {
        "common":"Saint Lucia",
        "cca2":"LC"
      },
      {
        "common":"Caribbean Netherlands",
        "cca2":"BQ"
      },
      {
        "common":"Bolivia",
        "cca2":"BO"
      },
      {
        "common":"Chile",
        "cca2":"CL"
      },
      {
        "common":"United States",
        "cca2":"US"
      },
      {
        "common":"Guadeloupe",
        "cca2":"GP"
      },
      {
        "common":"Mexico",
        "cca2":"MX"
      },
      {
        "common":"Saint Vincent and the Grenadines",
        "cca2":"VC"
      },
      {
        "common":"Bermuda",
        "cca2":"BM"
      },
      {
        "common":"Dominican Republic",
        "cca2":"DO"
      },
      {
        "common":"Guatemala",
        "cca2":"GT"
      },
      {
        "common":"Ecuador",
        "cca2":"EC"
      },
      {
        "common":"Martinique",
        "cca2":"MQ"
      },
      {
        "common":"Suriname",
        "cca2":"SR"
      },
      {
        "common":"Saint Barthélemy",
        "cca2":"BL"
      },
      {
        "common":"Bahamas",
        "cca2":"BS"
      },
      {
        "common":"Paraguay",
        "cca2":"PY"
      },
      {
        "common":"British Virgin Islands",
        "cca2":"VG"
      },
      {
        "common":"Brazil",
        "cca2":"BR"
      },
      {
        "common":"Belize",
        "cca2":"BZ"
      },
      {
        "common":"Venezuela",
        "cca2":"VE"
      },
      {
        "common":"El Salvador",
        "cca2":"SV"
      },
      {
        "common":"Peru",
        "cca2":"PE"
      },
      {
        "common":"Trinidad and Tobago",
        "cca2":"TT"
      },
      {
        "common":"Greenland",
        "cca2":"GL"
      },
      {
        "common":"Guyana",
        "cca2":"GY"
      },
      {
        "common":"Jamaica",
        "cca2":"JM"
      },
      {
        "common":"Aruba",
        "cca2":"AW"
      },
      {
        "common":"Cayman Islands",
        "cca2":"KY"
      },
      {
        "common":"Cuba",
        "cca2":"CU"
      },
      {
        "common":"Uruguay",
        "cca2":"UY"
      },
      {
        "common":"Saint Martin",
        "cca2":"MF"
      },
      {
        "common":"Antigua and Barbuda",
        "cca2":"AG"
      },
      {
        "common":"Canada",
        "cca2":"CA"
      },
      {
        "common":"Panama",
        "cca2":"PA"
      },
      {
        "common":"Montserrat",
        "cca2":"MS"
      },
      {
        "common":"Nicaragua",
        "cca2":"NI"
      },
      {
        "common":"Saint Pierre and Miquelon",
        "cca2":"PM"
      },
      {
        "common":"United States Virgin Islands",
        "cca2":"VI"
      },
      {
        "common":"Anguilla",
        "cca2":"AI"
      }
    ],
    "Europe":[
      {
        "common":"Norway",
        "cca2":"NO"
      },
      {
        "common":"Greece",
        "cca2":"GR"
      },
      {
        "common":"Åland Islands",
        "cca2":"AX"
      },
      {
        "common":"Switzerland",
        "cca2":"CH"
      },
      {
        "common":"Croatia",
        "cca2":"HR"
      },
      {
        "common":"Iceland",
        "cca2":"IS"
      },
      {
        "common":"Luxembourg",
        "cca2":"LU"
      },
      {
        "common":"Hungary",
        "cca2":"HU"
      },
      {
        "common":"Netherlands",
        "cca2":"NL"
      },
      {
        "common":"Lithuania",
        "cca2":"LT"
      },
      {
        "common":"Slovakia",
        "cca2":"SK"
      },
      {
        "common":"Liechtenstein",
        "cca2":"LI"
      },
      {
        "common":"Moldova",
        "cca2":"MD"
      },
      {
        "common":"Italy",
        "cca2":"IT"
      },
      {
        "common":"Jersey",
        "cca2":"JE"
      },
      {
        "common":"Monaco",
        "cca2":"MC"
      },
      {
        "common":"Belarus",
        "cca2":"BY"
      },
      {
        "common":"Latvia",
        "cca2":"LV"
      },
      {
        "common":"Andorra",
        "cca2":"AD"
      },
      {
        "common":"France",
        "cca2":"FR"
      },
      {
        "common":"Gibraltar",
        "cca2":"GI"
      },
      {
        "common":"Denmark",
        "cca2":"DK"
      },
      {
        "common":"North Macedonia",
        "cca2":"MK"
      },
      {
        "common":"Malta",
        "cca2":"MT"
      },
      {
        "common":"Czechia",
        "cca2":"CZ"
      },
      {
        "common":"Guernsey",
        "cca2":"GG"
      },
      {
        "common":"Kosovo",
        "cca2":"XK"
      },
      {
        "common":"Svalbard and Jan Mayen",
        "cca2":"SJ"
      },
      {
        "common":"Montenegro",
        "cca2":"ME"
      },
      {
        "common":"Faroe Islands",
        "cca2":"FO"
      },
      {
        "common":"Albania",
        "cca2":"AL"
      },
      {
        "common":"Serbia",
        "cca2":"RS"
      },
      {
        "common":"Ukraine",
        "cca2":"UA"
      },
      {
        "common":"Isle of Man",
        "cca2":"IM"
      },
      {
        "common":"Estonia",
        "cca2":"EE"
      },
      {
        "common":"Romania",
        "cca2":"RO"
      },
      {
        "common":"Bulgaria",
        "cca2":"BG"
      },
      {
        "common":"Germany",
        "cca2":"DE"
      },
      {
        "common":"Poland",
        "cca2":"PL"
      },
      {
        "common":"United Kingdom",
        "cca2":"GB"
      },
      {
        "common":"Finland",
        "cca2":"FI"
      },
      {
        "common":"Sweden",
        "cca2":"SE"
      },
      {
        "common":"Vatican City",
        "cca2":"VA"
      },
      {
        "common":"Russia",
        "cca2":"RU"
      },
      {
        "common":"Austria",
        "cca2":"AT"
      },
      {
        "common":"Cyprus",
        "cca2":"CY"
      },
      {
        "common":"Portugal",
        "cca2":"PT"
      },
      {
        "common":"Bosnia and Herzegovina",
        "cca2":"BA"
      },
      {
        "common":"Belgium",
        "cca2":"BE"
      },
      {
        "common":"Spain",
        "cca2":"ES"
      },
      {
        "common":"Slovenia",
        "cca2":"SI"
      },
      {
        "common":"San Marino",
        "cca2":"SM"
      },
      {
        "common":"Ireland",
        "cca2":"IE"
      }
    ],
    "Asia":[
      {
        "common":"South Korea",
        "cca2":"KR"
      },
      {
        "common":"Taiwan",
        "cca2":"TW"
      },
      {
        "common":"Jordan",
        "cca2":"JO"
      },
      {
        "common":"Nepal",
        "cca2":"NP"
      },
      {
        "common":"Thailand",
        "cca2":"TH"
      },
      {
        "common":"Kazakhstan",
        "cca2":"KZ"
      },
      {
        "common":"Georgia",
        "cca2":"GE"
      },
      {
        "common":"Pakistan",
        "cca2":"PK"
      },
      {
        "common":"Armenia",
        "cca2":"AM"
      },
      {
        "common":"Indonesia",
        "cca2":"ID"
      },
      {
        "common":"Japan",
        "cca2":"JP"
      },
      {
        "common":"Laos",
        "cca2":"LA"
      },
      {
        "common":"Lebanon",
        "cca2":"LB"
      },
      {
        "common":"Philippines",
        "cca2":"PH"
      },
      {
        "common":"Bahrain",
        "cca2":"BH"
      },
      {
        "common":"Qatar",
        "cca2":"QA"
      },
      {
        "common":"Tajikistan",
        "cca2":"TJ"
      },
      {
        "common":"China",
        "cca2":"CN"
      },
      {
        "common":"Yemen",
        "cca2":"YE"
      },
      {
        "common":"India",
        "cca2":"IN"
      },
      {
        "common":"Kuwait",
        "cca2":"KW"
      },
      {
        "common":"Syria",
        "cca2":"SY"
      },
      {
        "common":"Maldives",
        "cca2":"MV"
      },
      {
        "common":"Uzbekistan",
        "cca2":"UZ"
      },
      {
        "common":"Iran",
        "cca2":"IR"
      },
      {
        "common":"Myanmar",
        "cca2":"MM"
      },
      {
        "common":"Sri Lanka",
        "cca2":"LK"
      },
      {
        "common":"Bhutan",
        "cca2":"BT"
      },
      {
        "common":"Palestine",
        "cca2":"PS"
      },
      {
        "common":"Bangladesh",
        "cca2":"BD"
      },
      {
        "common":"Singapore",
        "cca2":"SG"
      },
      {
        "common":"Turkey",
        "cca2":"TR"
      },
      {
        "common":"United Arab Emirates",
        "cca2":"AE"
      },
      {
        "common":"Afghanistan",
        "cca2":"AF"
      },
      {
        "common":"Timor-Leste",
        "cca2":"TL"
      },
      {
        "common":"Vietnam",
        "cca2":"VN"
      },
      {
        "common":"Cambodia",
        "cca2":"KH"
      },
      {
        "common":"Iraq",
        "cca2":"IQ"
      },
      {
        "common":"Brunei",
        "cca2":"BN"
      },
      {
        "common":"Kyrgyzstan",
        "cca2":"KG"
      },
      {
        "common":"Azerbaijan",
        "cca2":"AZ"
      },
      {
        "common":"Hong Kong",
        "cca2":"HK"
      },
      {
        "common":"Malaysia",
        "cca2":"MY"
      },
      {
        "common":"Mongolia",
        "cca2":"MN"
      },
      {
        "common":"Saudi Arabia",
        "cca2":"SA"
      },
      {
        "common":"Turkmenistan",
        "cca2":"TM"
      },
      {
        "common":"North Korea",
        "cca2":"KP"
      },
      {
        "common":"Israel",
        "cca2":"IL"
      },
      {
        "common":"Oman",
        "cca2":"OM"
      },
      {
        "common":"Macau",
        "cca2":"MO"
      }
    ],
    "Africa":[
      {
        "common":"Lesotho",
        "cca2":"LS"
      },
      {
        "common":"Central African Republic",
        "cca2":"CF"
      },
      {
        "common":"Morocco",
        "cca2":"MA"
      },
      {
        "common":"Sierra Leone",
        "cca2":"SL"
      },
      {
        "common":"Burkina Faso",
        "cca2":"BF"
      },
      {
        "common":"Eritrea",
        "cca2":"ER"
      },
      {
        "common":"Tanzania",
        "cca2":"TZ"
      },
      {
        "common":"Algeria",
        "cca2":"DZ"
      },
      {
        "common":"Mauritania",
        "cca2":"MR"
      },
      {
        "common":"Sudan",
        "cca2":"SD"
      },
      {
        "common":"Western Sahara",
        "cca2":"EH"
      },
      {
        "common":"Angola",
        "cca2":"AO"
      },
      {
        "common":"Ivory Coast",
        "cca2":"CI"
      },
      {
        "common":"Tunisia",
        "cca2":"TN"
      },
      {
        "common":"Mali",
        "cca2":"ML"
      },
      {
        "common":"Benin",
        "cca2":"BJ"
      },
      {
        "common":"Cape Verde",
        "cca2":"CV"
      },
      {
        "common":"Equatorial Guinea",
        "cca2":"GQ"
      },
      {
        "common":"Uganda",
        "cca2":"UG"
      },
      {
        "common":"Botswana",
        "cca2":"BW"
      },
      {
        "common":"Burundi",
        "cca2":"BI"
      },
      {
        "common":"South Africa",
        "cca2":"ZA"
      },
      {
        "common":"Libya",
        "cca2":"LY"
      },
      {
        "common":"Mayotte",
        "cca2":"YT"
      },
      {
        "common":"Gabon",
        "cca2":"GA"
      },
      {
        "common":"Cameroon",
        "cca2":"CM"
      },
      {
        "common":"Guinea",
        "cca2":"GN"
      },
      {
        "common":"Seychelles",
        "cca2":"SC"
      },
      {
        "common":"British Indian Ocean Territory",
        "cca2":"IO"
      },
      {
        "common":"Madagascar",
        "cca2":"MG"
      },
      {
        "common":"DR Congo",
        "cca2":"CD"
      },
      {
        "common":"Gambia",
        "cca2":"GM"
      },
      {
        "common":"Somalia",
        "cca2":"SO"
      },
      {
        "common":"Nigeria",
        "cca2":"NG"
      },
      {
        "common":"South Sudan",
        "cca2":"SS"
      },
      {
        "common":"Eswatini",
        "cca2":"SZ"
      },
      {
        "common":"Egypt",
        "cca2":"EG"
      },
      {
        "common":"Saint Helena, Ascension and Tristan da Cunha",
        "cca2":"SH"
      },
      {
        "common":"Senegal",
        "cca2":"SN"
      },
      {
        "common":"Togo",
        "cca2":"TG"
      },
      {
        "common":"Kenya",
        "cca2":"KE"
      },
      {
        "common":"Rwanda",
        "cca2":"RW"
      },
      {
        "common":"Namibia",
        "cca2":"NA"
      },
      {
        "common":"Liberia",
        "cca2":"LR"
      },
      {
        "common":"Zambia",
        "cca2":"ZM"
      },
      {
        "common":"Niger",
        "cca2":"NE"
      },
      {
        "common":"Comoros",
        "cca2":"KM"
      },
      {
        "common":"Guinea-Bissau",
        "cca2":"GW"
      },
      {
        "common":"Ghana",
        "cca2":"GH"
      },
      {
        "common":"Chad",
        "cca2":"TD"
      },
      {
        "common":"Zimbabwe",
        "cca2":"ZW"
      },
      {
        "common":"Réunion",
        "cca2":"RE"
      },
      {
        "common":"São Tomé and Príncipe",
        "cca2":"ST"
      },
      {
        "common":"Malawi",
        "cca2":"MW"
      },
      {
        "common":"Ethiopia",
        "cca2":"ET"
      },
      {
        "common":"Republic of the Congo",
        "cca2":"CG"
      },
      {
        "common":"Djibouti",
        "cca2":"DJ"
      },
      {
        "common":"Mauritius",
        "cca2":"MU"
      },
      {
        "common":"Mozambique",
        "cca2":"MZ"
      }
    ],
    "Oceania":[
      {
        "common":"New Caledonia",
        "cca2":"NC"
      },
      {
        "common":"Solomon Islands",
        "cca2":"SB"
      },
      {
        "common":"Marshall Islands",
        "cca2":"MH"
      },
      {
        "common":"Vanuatu",
        "cca2":"VU"
      },
      {
        "common":"Niue",
        "cca2":"NU"
      },
      {
        "common":"Nauru",
        "cca2":"NR"
      },
      {
        "common":"Cocos (Keeling) Islands",
        "cca2":"CC"
      },
      {
        "common":"Fiji",
        "cca2":"FJ"
      },
      {
        "common":"Wallis and Futuna",
        "cca2":"WF"
      },
      {
        "common":"Cook Islands",
        "cca2":"CK"
      },
      {
        "common":"Australia",
        "cca2":"AU"
      },
      {
        "common":"Tuvalu",
        "cca2":"TV"
      },
      {
        "common":"Pitcairn Islands",
        "cca2":"PN"
      },
      {
        "common":"Christmas Island",
        "cca2":"CX"
      },
      {
        "common":"Guam",
        "cca2":"GU"
      },
      {
        "common":"Tonga",
        "cca2":"TO"
      },
      {
        "common":"Tokelau",
        "cca2":"TK"
      },
      {
        "common":"Samoa",
        "cca2":"WS"
      },
      {
        "common":"Kiribati",
        "cca2":"KI"
      },
      {
        "common":"French Polynesia",
        "cca2":"PF"
      },
      {
        "common":"Papua New Guinea",
        "cca2":"PG"
      },
      {
        "common":"Palau",
        "cca2":"PW"
      },
      {
        "common":"American Samoa",
        "cca2":"AS"
      },
      {
        "common":"Northern Mariana Islands",
        "cca2":"MP"
      },
      {
        "common":"Norfolk Island",
        "cca2":"NF"
      },
      {
        "common":"New Zealand",
        "cca2":"NZ"
      },
      {
        "common":"Micronesia",
        "cca2":"FM"
      }
    ]
  }
]

export interface world {
  America: Continent[];
  Europe: Continent[];
  Asia: Continent[];
  Africa: Continent[];
  Oceania: Continent[];
}

interface Continent {
  common: string;
  cca2: string;
}